LMS/urls.py
from django.urls import path, include
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]

library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
    path("register/", views.registerPage, name="register"),
    path("add_new_student/", views.add_new_student, name="new_student"),
    path("add_new_book/", views.add_new_book, name="new_book"),
    path("add_book_issue/", views.add_book_issue, name="book_issue"),
    path(
        "add_new_book_instance/",
        views.add_new_book_instance,
        name="add_new_book_instance",
    ),
    path("show_students/", views.view_students, name="show_student_record"),
    path("view_books/", views.view_books, name="show_book_record"),
    path("view_books_issued/", views.view_bissue, name="show_issue_record"),
    path("edit/student/<str:roll>", views.edit_student_data, name="Edit_Student_data"),
    path(
        "/view_books/edit/book/<uuid:id>", views.edit_book_data, name="Edit_book_data"
    ),
    path(
        "delete/student/<str:roll>",
        views.delete_student,
        name="Delete_Student_data",
    ),
    path(
        "view_books/delete/book/<uuid:id>", views.delete_book, name="Delete book data"
    ),
    path(
        "view_books_issued/return_book/<int:id>",
        views.return_issued_book,
        name="return_issued_book",
    ),
    path("edit_issued/<int:id>", views.edit_issued, name="edit_issued"),
]

library/models.py
from django.db import models
from datetime import datetime, timedelta
import uuid


class Students(models.Model):
    roll_number = models.CharField(max_length=100, unique=True)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    program = models.CharField(max_length=100)
    Guardian_name = models.CharField(
        max_length=100, help_text="parent/guardian full name"
    )
    Email = models.EmailField(max_length=100, help_text="Guardian/parent e-mail")

    def __str__(self):
        return self.fullname


class Book(models.Model):
    book_title = models.CharField(max_length=200)
    book_author = models.CharField(max_length=100)
    book_pages = models.PositiveIntegerField()
    summary = models.TextField(
        max_length=500, help_text="Summary about the book", null=True, blank=True
    )

    def __str__(self):
        return self.book_title


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Book unique id across the Library",
    )
    book = models.ForeignKey("Book", on_delete=models.CASCADE, null=True)
    book_number = models.PositiveIntegerField(
        null=True, help_text="Book number for books of the save kind"
    )
    Is_borrowed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id} {self.book}"


def get_returndate():
    return datetime.today() + timedelta(days=8)


class Book_Issue(models.Model):
    student = models.ForeignKey("Students", on_delete=models.CASCADE)
    book_instance = models.ForeignKey("BookInstance", on_delete=models.CASCADE)
    issue_date = models.DateTimeField(
        auto_now=True, help_text="Date the book is issued"
    )
    due_date = models.DateTimeField(
        default=get_returndate(), help_text="Date the book is due to"
    )
    date_returned = models.DateField(
        null=True, blank=True, help_text="Date the book is returned"
    )
    remarks_on_issue = models.CharField(
        max_length=100,
        default="Book in good condition",
        help_text="Book remarks/condition during issue",
    )
    remarks_on_return = models.CharField(
        max_length=100,
        default="Book in good condition",
        help_text="Book remarks/condition during return",
    )

    def __str__(self):
        return self.student.fullname + " borrowed " + self.book.book_title

library/forms.py
from django import forms
from .models import Students, Book, Book_Issue,BookInstance

class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        
class Book_instanceForm(forms.ModelForm):
    class Meta:
        model=BookInstance
        fields = ['book','book_number']

class Book_IssueForm(forms.ModelForm):
    class Meta:
        model=Book_Issue
        exclude = ['issue_date', 'due_date','remarks_on_return','date_returned']

library/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .forms import StudentsForm, BookForm, Book_IssueForm, Book_instanceForm
from .models import Students, Book, Book_Issue, BookInstance
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# CONSTANTS
CollegeKeyPass = 1234


# @login_required(login_url="login")

# def homePage(request):
#     return render(request, "home.html", {"username": request.user.username})


# loginpage
def loginPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            return HttpResponse("Username or Password is incorrect!!!")
    return render(request, "login.html")


# logoutpage
def logoutPage(request):
    logout(request)
    return redirect("login")


# registerpage
def registerPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        ckp = int(request.POST["clgkeypass"])
        email = request.POST["email"]
        pass1 = request.POST["password1"]
        pass2 = request.POST["password2"]

        if ckp == CollegeKeyPass:
            if pass1 != pass2:
                return HttpResponse("Passwords Did Not Matched")
            else:
                my_user = User.objects.create_user(username, email, pass1)
                my_user.save()
                return redirect("login")
        else:
            return HttpResponse("College Key Pass is Incorrect")
    return render(request, "register.html")


# @login_required(login_url="login")
def index(request):
    return render(request, "index.html")


@login_required(login_url="login")
def add_new_student(request):
    if request.method == "POST":
        form = StudentsForm((request.POST))
        if form.is_valid():
            form.save()
            return redirect("/show_students")
    else:
        form = StudentsForm
    return render(request, "add_new_student.html", {"form": form})


@login_required(login_url="login")
def add_new_book(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form = form.save()
            book_instance = BookInstance(book=form)
            book_instance.save()
            return redirect("/view_books")
    else:
        form = BookForm
        form_instance = Book_instanceForm
        return render(
            request, "add_new_book.html", {"form": form, "form_instance": form_instance}
        )


@login_required(login_url="login")
def add_new_book_instance(request):
    if request.method == "POST":
        form = Book_instanceForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("/view_books")
    return HttpResponse("Problem")


@login_required(login_url="login")
def add_book_issue(request):
    if request.method == "POST":
        form = Book_IssueForm(request.POST)
        if form.is_valid():
            # save data
            unsaved_form = form.save(commit=False)
            book_to_save = BookInstance.objects.get(id=unsaved_form.book_instance.id)
            book_to_save.Is_borrowed = True
            book_to_save.save()
            form.save()
            form.save_m2m()
        return redirect("/view_books_issued")
    else:
        print("helloooo")
        context = {
            "form": Book_IssueForm,
            "book": BookInstance.objects.filter(Is_borrowed=False),
        }
        return render(request, "add_book_issue.html", context=context)


@login_required(login_url="login")
def view_students(request):
    students = Students.objects.order_by("-id")
    return render(request, "view_students.html", {"students": students})


@login_required(login_url="login")
def view_books(request):
    books = BookInstance.objects.order_by("id")
    return render(request, "view_books.html", {"books": books})


@login_required(login_url="login")
def view_bissue(request):
    issue = Book_Issue.objects.order_by("-id")
    return render(request, "issue_records.html", {"issue": issue})


@login_required(login_url="login")
def edit_student_data(request, roll):
    try:
        if request.method == "POST":
            std = Students.objects.get(id=request.session["id"])
            form = StudentsForm((request.POST), instance=std)
            if form.is_valid():
                form.save()
            del request.session["id"]
            return redirect("/show_students")
        else:
            student_to_edit = Students.objects.get(roll_number=roll)
            student = StudentsForm(instance=student_to_edit)
            request.session["id"] = student_to_edit.id
            return render(request, "edit_student_data.html", {"student": student})
    except Exception as error:
        print(f"{error} occured at edit_student_data view")


@login_required(login_url="login")
def edit_book_data(request, id):
    return HttpResponse(
        f"<label>A book with ID: {id} could not be edited...</label><h2>The feature is comming soon</h2>"
    )


@login_required(login_url="login")
def delete_student(request, roll):
    return HttpResponse(
        f"<h2>Delete Student</h2><label>Student with Roll Number: {roll} could not be deleted...</label><h2>The feature is comming soon</h2>"
    )
    pass


@login_required(login_url="login")
def delete_book(request, id):
    # obj = get_object_or_404(Book, id=id)
    book_to_delete = get_object_or_404(Book, id=id)
    book_to_delete.delete()
    # book_to_save = Book.objects.get(id=id)
    # book_to_save.delete()
    # return redirect("view_books/")
    return HttpResponse(
        f"<h2>Delete Book</h2><label>Book with ID: {id} could not be deleted..</label><h2>The feature is comming soon</h2>"
    )


@login_required(login_url="login")
def return_issued_book(request, id):
    book_issue = get_object_or_404(Book_Issue, id=id)
    if book_issue:
        book_to_save = BookInstance.objects.get(id=book_issue.book_instance.id)
        book_to_save.Is_borrowed = False

        book_to_save.save()

        book_issue.delete()

        return redirect("/view_books_issued")
    return HttpResponse("book not found")


@login_required(login_url="login")
def edit_issued(request, id):
    obj = Book_Issue.objects.get(id=id)
    return HttpResponse(
        f"<h2>Edit Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be edited..</label><h2>The feature is comming soon</h2>"
    )

library/templates/add_book_issue.html
<title>Add Book Issue</title>
{% extends 'base.html' %}

<body>
{% block content %}
<div class = "d-flex justify-content-center fs-3">
<form method="POST" action="{% url 'book_issue' %}" class="form-inline">
    {% csrf_token %}
    <label class = "fs-3">Student Details(Name)</label><br>
    <div id="student_selection">
        <div>{{form.student}}</div>
            <div><input type="text" placeholder="Quick Student Search" id="quick" onkeyup="Quick_search()">
                <div id="quick_student_search_view"></div>
            </div>
    </div>

    <br>
    <hr>
        <div class="book_selection">
            <label class = "fs-3">Book Details(Name/UUID)</label>
            <br>
            <div><input type="text" placeholder="Quick Book Search" id="quick_book_search" onkeyup="Quick_book_search()">
                <div id="quick_book_search_view"></div>
            </div>
            <select name="book_instance" required id="id_book_instance">
                <option value="" selected>---------</option>
                {%for i in book%}
                    <option class="selection" value="{{i.id}}">{{i.book.book_title}} (: {{i.id}})</option>
                {%endfor%}
            </select>
        </div>
    <hr>
    <label class = "fs-3">Remarks</label><br> <div> {{form.remarks_on_issue}}</div>
    <br> 
    <button type="submit" class="btn btn-success fs-4 p-3">Issue Book</button>
</form>
</div>


<script type="text/javascript">
    function Quick_search(){
        var input, items,view;
        input = document.getElementById('quick').value.toLowerCase();
        items = document.getElementById('id_student');
        view=document.getElementById("quick_student_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if(input !== "" && (item.toLowerCase().indexOf(input)>-1 )){
                    var list_added = document.createElement("label");
                    list_added.appendChild(document.createTextNode(item));
                    list_added.onclick =function(){
                        items.children[get_clicked_value(this.innerHTML)].setAttribute("selected",true);
                        view.style.display="none";
                        // uncomment below line to hide the search input after selection is made
                        // document.getElementById('quick').style.display="none";
                    };
                    view.appendChild(list_added);
                    view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function get_clicked_value(clicked){
        var items = document.getElementById('id_student');
        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i];
                if (item.innerHTML == clicked ) {
                    return item.getAttribute("value");
                }
        }
    }

    // Quick book search
    function Quick_book_search(){
        var input, items,view;
        input = document.getElementById('quick_book_search');
        items = document.getElementById('id_book_instance');
        view=document.getElementById("quick_book_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if((input.value.toLowerCase() !== "") && (item.toLowerCase().indexOf(input.value.toLowerCase())>-1 ) ){
                var list_added = document.createElement("label");
                list_added.appendChild(document.createTextNode(item));
                list_added.onclick =function(){
                    select_clicked_book(this.innerHTML);
                    view.style.display="none";
                    // comment below line to unhide the search input after selection is made
                    input.style.display="none"; input.value="";
                };
                view.appendChild(list_added);
                view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function select_clicked_book(clicked){
        var books = document.getElementById('id_book_instance');   
        for(i=1;i<books.children.length.valueOf();i++){
            var item=books.children[i];
                if (item.innerHTML == clicked ) {
                    item.setAttribute("selected",true);
                }
        }
    }
</script>
{% endblock %}
</body>
</html>

library/templates/add_new_book.html
<title>Add New Book</title>
{% extends 'base.html' %}

<body>
{% block content %}

    <div class="tablinks fs-2 p-2 py-4 d-flex justify-content-around">
        <button onclick="opentab(name)" class="link btn btn-primary fs-3 px-3 mx-3 " name="new_book">New Book</button>
        <button onclick="opentab(name)" class="link btn btn-primary fs-3" name="new_book_instance">New Book Instance</button>
    </div>

    <div id="new_book" class="books d-flex justify-content-center fs-2">
        <form method="POST" action="" class="form-inline">
            {% csrf_token %}
        <label>Book Title.</label><br><div>{{form.book_title}}</div>
        <label>Book Author.</label><br> <div> {{form.book_author}}</div>
        <label>Book Pages.</label><br> <div> {{form.book_pages}}</div>
        <label>Book summary<i>(if any)</i></label><br> <div> {{form.summary}}</div>
        <!-- <div>
            <label>Multiple Same Books</label>    
            <input type="radio" name="mode" id="multiple" value="Multiple" onclick="toggle_quantity_input(id)">
            <label>Single  book</label>    
            <input type="radio" value="single" name="mode" id="single" onclick="toggle_quantity_input(id)">

            <div id="additional_data">
                <b>Note:<i>For multiple copies, separate book number with a comma (',')</i> </b>
                <div id="multi">
                    <label>Enter the Book Quantity</label><br>
                    <input type="number" min="1" name="book_quantity"><br>
                </div>  
                <label >Book Number(if any) </label><br>
                <input name="book_number_list">
            </div>
        </div> -->
        <br> <button type="submit" class="btn btn-success fs-3">Add Book</button> 
        </form>
    </div>

    <div id="new_book_instance fs-3" class="books">
        <form method="POST" action="{% url 'add_new_book_instance' %}" class="form-inline">
            {% csrf_token %}
            <label>Book</label><br><div>{{form_instance.book}}</div>
            <label>Book Number</label>
            <div>{{form_instance.book_number}}</div>
            <br> <button type="submit" class="btn btn-success">Add Book</button> 
        </form>
    </div>

<script type="text/javascript">
    function opentab(tab_name){
         var tab=document.getElementById(tab_name);
         var i, tabcontent, tablinks;
         tabcontent = document.getElementsByClassName("books");
         for (i = 0; i < tabcontent.length; i++) {
             tabcontent[i].style.display = "none";
         }
         tablinks = document.getElementsByClassName("link");
         for (i = 0; i < tablinks.length; i++) {
             tablinks[i].className = tablinks[i].className.replace(" active", "");
         }
         tab.style.display = "block";

    }
    // function toggle_quantity_input(id){
    //     var obj=document.getElementById("multi");
    //     document.getElementById("additional_data").style.display="block";
    //     if(id=="single"){
    //         obj.style.display="none";
    //     }
    //     else{
    //         obj.style.display="block";   
    //     }
    // }
</script>

{% endblock %}
</body>

</html>

library/templates/add_new_student.html
<title>Add New Student</title>
{% extends 'base.html' %} {% load static %}
<html>
  <body>
    {% block content %}
    <div class="">
      <div class="form d-flex justify-content-center Roboto">
        <form method="POST" action="">
          {% csrf_token %}
          <label class="label-default form-label">Student Details</label><br />

          <label class="form-label">Roll Number:</label><br />
          <div>{{form.roll_number}}</div>

          <label class="form-label">Student Name:</label><br />
          <div>{{form.fullname}}</div>
          <label class="form-label">Student Address:</label><br />
          <div>{{form.address}}</div>
          <label class="form-label">Student Study Program:</label><br />
          <div>{{form.program}}</div>
          <br />
          <label class="label-default form-label"
            >Student Guardian/Parent Details</label
          ><br />

          <label class="form-label">Full name:</label><br />
          <div>{{form.Guardian_name}}</div>
          <label class="form-label">Valid Email:</label><br />
          <div>{{form.Email}}</div>
          <br />
          <div>
            <button type="submit" class="btn btn-success">Add Student</button>
          </div>
        </form>
      </div>
    </div>

    {% endblock %}
  </body>
</html>

library/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {%load static%}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{%static 'icon/css/all.css' %}" />
    <link rel="stylesheet" href="{%static 'css/style.css' %}" />
    <link rel="stylesheet" href="{%static 'css/css2.css' %}" />
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <!-- https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css -->
    <script src="{%static 'js/jquery.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js -->
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <!-- downloaded via https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js -->
    <!-- <script src="{%static 'js/functions.js' %}"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  
    <style>
      *{
        font-family: "Times New Roman", Times, serif;
      }
      body {
        background-image: url("static/images/bg_library.jpg");
        text-align: center;
      }

      form {
        margin-top: 13em;
      }

      .custom-navbar {
        background-color: #442a00 !important;
        border: none;
        border-radius: 0;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
      }

      .custom-navbar .custom-brand {
        color: #ffffff;
        font-size: 20px;
      }

      .custom-nav {
        margin-top: 10px;
      }

      .custom-nav li a {
        color: #ffffff;
      }
      li {
        display: flex;
        align-items: center;
        justify-content: center;
      }
      .custom-nav li a:hover {
        color: #91b200 !important;
        /* text-shadow: #74d22c; */
      }

      .custom-logout {
        /* margin-top: 7px; */
        margin-left: 10px;
        padding: 5px 10px;
        border-radius: 3px;
        background-color: #cccc8e !important;
        color: rgb(0, 0, 0) !important;
        font-weight: bold;
        text-transform: uppercase;
        letter-spacing: 1px;
      }

      .custom-logout:hover {
        background-color: #c4c452 !important;
        color: #020202 !important;
        text-decoration: none;
      }
      .logout-button {
        text-align: center;
      }

      .navbar {
        list-style: none;
        display: flex;
      }

      .nav-link {
        text-decoration: none;
        color: #333;
        margin-right: 15px;
      }

      .nav-link.active {
        font-weight: bold;
        color: #007bff; /* Active link color */
      }
      body{
        background-image: linear-gradient(to right, #00b09b, #96c93d);
      }

      .heading{
        font-family: sans-serif;
  
  line-height: 1.6; 
  color: #333; 
  background-color: #f0f0f0;
  padding : 0.5rem;
      }

      form{
        display : grid;
        grid-templates-column : 1fr;
        margin-left : 0px;
        margin-top : 1rem;
        font-size : 1.3rem;
        background-color : #d0bdf4;
        
      }
      .card{
        padding : 0.5rem;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid ">
        {% comment %} <div class="navbar-header">
          <label class="navbar-brand">LIBRARY MANAGEMENT SYSTEM</label>
        </div> {% endcomment %}
        <ul class="nav navbar-nav d-flex flex-row d-flex justify-content-center align-items-center  text-light">
          <li class = 'fs-2 px-2' ><b>LIBRARY MANAGEMENT SYSTEM</b></li>
          <li class = 'nav-link fs-3 px-2'><a href="/">Home</a></li>
          <li class = 'fs-3 px-2'>
            <a href="{% url 'new_student' %}" class="nav-link">Add Student</a>
          </li>
          <li class = 'fs-3 px-2'><a href="{% url 'new_book' %}" class="nav-link">Add Book</a></li>
          <li class = 'fs-3 px-2'>
            <a href="{% url 'book_issue' %}" class="nav-link">Add Issue Book</a>
          </li class = 'fs-3 px-2'>
          <li class = 'fs-3 px-2'>
            <a href="{% url 'show_student_record' %}" class="nav-link"
              >Students</a
            >
          </li>
          <li class = 'fs-3 px-2'>
            <a href="{% url 'show_book_record' %}" class="nav-link">Books</a>
          </li>
          <li class = 'fs-3 px-2'>
            <a href="{% url 'show_issue_record' %}" class="nav-link"
              >Books Issued</a
            >
          </li>
          {% if request.user.is_authenticated %}
          <li class = ''>
            <a href="{% url 'logout' %}" class="btn btn-primary text-light fs-3" ><b>Logout<b></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock %}
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
    integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
    crossorigin="anonymous"
  ></script>
  
  </script>
</html>

library/templates/edit_student_data.html
<title>Edit Student</title>
{% extends 'base.html' %}

<body>
{% block content %}

<div class="form">
<form method="POST" action=""  id="edit_student_data">
    {% csrf_token %}
    <label>Details</label>
    <label>Roll Number:</label><br>
    {{student}}
    <!-- <input type="text" name="roll_number" value={{student.roll_number}} required><br>
    <label>Student Name:</label><br>
    <input type="text" name="student_name" value={{student.fullname}} required><br>
    <label>Student Address:</label><br> 
    <input type="text" name="address" value={{student.address}} required><br>
    <label>Student Study Program:</label><br> 
    <input type="text" name="program" value={{student.program}} required><br>
    <label>Student Guardian/Parent Details</label><br>
    <label>Full name:</label><br> 
    <input type="text" name="Guardian_name" value={{student.Guardian_name}} required><br>
    <label>Valid Email:</label><br> 
    <input type="email" name="email" value="{{student.Email}}" required><br> -->
    <br> <button type="submit" class="btn btn-success">OK</button>
</form>
</div>
{% endblock %}
</body>

</html>

library/templates/issue_records.html
<title> Issue Records </title>
{% extends 'base.html' %}

<body>
{% block content %}
<table class="table table-striped table  table-warning table-striped-columns table-hover px-2 fs-2">
<tr class = "text-center">
    <th class = "table-primary border border-light">Student name </th>
    <th class = "table-primary border border-light">Book ID </th>
    <th class = "table-primary border border-light">Issue Date </th>
    <th class = "table-primary border border-light">Due Date</th>
    <th class = "table-primary border border-light">Remarks on Issuing</th>
    <th class = "table-primary border border-light">Remarks on Return</th>
    <th class = "table-primary border border-light">Returned</th>
    <th class = "table-primary border border-light">Book Return</th>
</tr>
    {%for i in issue%}
    <tr>
        <td>{{i.student}}</td>
        <td>{{i.book_instance.id}}</td>
        <td>{{i.issue_date}}</td>
        <td>{{i.due_date}}</td>
        <td>{{i.remarks_on_issue}}</td>
        <td>{{i.remarks_on_return}}</td>
        <td>
            {%if i.book_instance.Is_borrowed %}
            <span><i class="fa fa-times-circle" style="color:rgb(128, 28, 0)"></i></span>
            <td>
                <a href="return_book/{{i.id}}"><i class="fa fa-arrow-alt-circle-right"></i><i class="fa fa-book"></i></a>|
                
                
            </td>
            {%else%}
            <span><i class="fa fa-check-circle" style="color:green"></i></span>
            <td><a href="edit_issued/{{i.id}}"><i class="fa fa-edit"></i> </a> | <a href="delete_issued/{{i.id}}"><i class="fa fa-trash-alt"></i></a></td>
            {%endif%}
        </td>

        
        
    </tr> {% endfor %}
</table>

{% endblock %}
</body>
</html>